### ISSUE TITLE
'RUSTFLAGS' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by Tsjippy** [signalapp/zkgroup#10]
When trying to compile on windows with `"C:\Program Files (x86)\GnuWin32\bin\make.exe" libzkgroup` I get this:

> RUSTFLAGS='-C link-arg=-s' cargo build --release
> 'RUSTFLAGS' is not recognized as an internal or external command,
> operable program or batch file.
> make: *** [libzkgroup] Fout 1

How do I fix that?

**Comment by dennisameling** [comment]
Do you have Git for Windows installed? You can try running the same command with Git Bash, it'll work then. This way of setting parameters is a Unix-only thing AFAIK.

**Comment by Tsjippy** [comment]
That works thank you very much!
